# Generated by Django 3.2 on 2021-07-14 15:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_newuser_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('Hall', 'Hall'), ('Musician', 'Musician'), ('Comedy', 'Comedy'), ('Photographer', 'Photographer'), ('PartyPlaner', 'PartyPlaner')], default='Musician', max_length=15)),
                ('office_number', models.CharField(blank=True, max_length=11)),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('zipcode', models.CharField(max_length=5)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('deposit', models.PositiveSmallIntegerField(blank=True, verbose_name='Upfront Deposit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photographer')),
                ('charge_mile', models.PositiveSmallIntegerField(verbose_name='charge/mile')),
                ('price_small', models.PositiveSmallIntegerField(blank=True, verbose_name='price/small event')),
                ('price_wedding', models.PositiveSmallIntegerField(blank=True, verbose_name='price/wedding')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PartyPlaner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='party')),
                ('charge_mile', models.PositiveSmallIntegerField(verbose_name='charge/mile')),
                ('price_small', models.PositiveSmallIntegerField(blank=True, verbose_name='price/small event')),
                ('price_wedding', models.PositiveSmallIntegerField(blank=True, verbose_name='price/wedding')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Keyboard', 'Keyboard Player'), ('Singer', 'Singer'), ('Guitar', 'Guitar'), ('Saxophone', 'Saxophone'), ('Trumped', 'Trumped')], max_length=15)),
                ('image', models.ImageField(blank=True, upload_to='comedy')),
                ('charge_mile', models.PositiveSmallIntegerField(verbose_name='charge/mile')),
                ('charge_lead', models.PositiveSmallIntegerField(blank=True, verbose_name='charge/lead band')),
                ('band_arrange', models.PositiveSmallIntegerField(blank=True, verbose_name='band arrangement cost')),
                ('price_man', models.PositiveSmallIntegerField(blank=True, verbose_name='price/man')),
                ('price_small', models.PositiveSmallIntegerField(blank=True, verbose_name='price/small event')),
                ('price_wedding', models.PositiveSmallIntegerField(blank=True, verbose_name='price/wedding')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='halls')),
                ('couples', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(120)])),
                ('cost_per_couple', models.PositiveSmallIntegerField(blank=True, verbose_name='cost/couple')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Comedy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='comedy')),
                ('charge_mile', models.PositiveSmallIntegerField(verbose_name='charge/mile')),
                ('price_small', models.PositiveSmallIntegerField(blank=True, verbose_name='price/small event')),
                ('price_wedding', models.PositiveSmallIntegerField(blank=True, verbose_name='price/wedding')),
                ('price_hour', models.PositiveSmallIntegerField(blank=True, verbose_name='price/hour')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.supplier')),
            ],
        ),
    ]
