# Generated by Django 3.2 on 2021-07-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_comedy_hall_musician_partyplaner_photographer_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.CharField(choices=[('Hall', 'Hall'), ('Comedy', 'Comedy'), ('Photographer', 'Photographer'), ('PartyPlaner', 'PartyPlaner'), ('Musician', 'Musician')], default='Musician', max_length=15),
        ),
    ]
