# Generated by Django 3.2 on 2021-07-14 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_supplier_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedy',
            name='charge_mile',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='charge/mile'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='couples',
            field=models.PositiveSmallIntegerField(blank=True, default=20, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='musician',
            name='charge_mile',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='charge/mile'),
        ),
        migrations.AlterField(
            model_name='partyplaner',
            name='charge_mile',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='charge/mile'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='charge_mile',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='charge/mile'),
        ),
    ]
