# Generated by Django 3.2 on 2021-07-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210714_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='country',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.CharField(choices=[('Hall', 'Hall'), ('Comedy', 'Comedy'), ('Photographer', 'Photographer'), ('PartyPlaner', 'PartyPlaner'), ('Musician', 'Musician')], max_length=15),
        ),
    ]
