# Generated by Django 3.2 on 2021-08-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210715_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.CharField(blank=True, choices=[('Hall', 'Hall'), ('Comedy', 'Comedy'), ('Photographer', 'Photographer'), ('PartyPlaner', 'PartyPlaner'), ('Musician', 'Musician')], max_length=15),
        ),
    ]
