# Generated by Django 3.2 on 2021-08-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_supplier_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.CharField(choices=[('Hall', 'Hall'), ('Comedy', 'Comedy'), ('Photographer', 'Photographer'), ('Musician', 'Musician'), ('PartyPlaner', 'PartyPlaner')], max_length=15),
        ),
    ]
