# Generated by Django 3.2 on 2021-08-10 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_partyplaner_price_small'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='party')),
                ('charge_mile', models.PositiveSmallIntegerField(blank=True, verbose_name='charge/mile')),
                ('price_small', models.PositiveSmallIntegerField(blank=True, verbose_name='price/small event')),
                ('price_wedding', models.PositiveSmallIntegerField(blank=True, verbose_name='price/wedding')),
            ],
        ),
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.CharField(choices=[('Hall', 'Hall'), ('Comedy', 'Comedy'), ('Photographer', 'Photographer'), ('Musician', 'Musician'), ('Party', 'Party')], max_length=15),
        ),
        migrations.DeleteModel(
            name='PartyPlaner',
        ),
        migrations.AddField(
            model_name='party',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.supplier'),
        ),
    ]
