# Generated by Django 3.2 on 2021-08-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210810_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='type',
            field=models.CharField(choices=[('Keyboard', 'Keyboard'), ('Singer', 'Singer'), ('Guitar', 'Guitar'), ('Saxophone', 'Saxophone'), ('Trumped', 'Trumped')], max_length=15),
        ),
    ]
