# Generated by Django 3.2 on 2021-08-10 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_musician_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='type',
            new_name='tool',
        ),
    ]
