# Generated by Django 3.2 on 2021-08-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_rename_type_musician_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='image',
            field=models.ImageField(blank=True, upload_to='musician'),
        ),
    ]
