# Generated by Django 3.2 on 2021-08-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20210810_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='tool',
            field=models.CharField(blank=True, choices=[('keyboard', 'keyboard'), ('singer', 'singer'), ('guitar', 'guitar'), ('saxophone', 'saxophone'), ('trumped', 'trumped')], default='singer', max_length=15),
            preserve_default=False,
        ),
    ]
