# Generated by Django 3.2 on 2021-08-27 14:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_musician_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='couples',
            field=models.PositiveSmallIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=11, verbose_name='contact no#')),
                ('type', models.CharField(choices=[('Small Event', 'Small Event'), ('Wedding', 'Wedding'), ('Family', 'Family')], max_length=15)),
                ('category', models.CharField(max_length=15)),
                ('couple', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('couple_cost', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hour_cost', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='hour cost')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('distance_charges', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Distance Charges')),
                ('event_cost', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Event Cost')),
                ('wedding_cost', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Wedding Cost')),
                ('band_arrange', models.BooleanField()),
                ('charge_lead', models.BooleanField()),
                ('man', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='total gathering')),
                ('price_man', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='price/man')),
                ('total', models.PositiveSmallIntegerField(blank=True, verbose_name='Total Cost')),
                ('address', models.TextField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
