# Generated by Django 3.2 on 2021-08-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20210827_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Upfront Deposit'),
            preserve_default=False,
        ),
    ]
